table 'Dataset Marketing'
	lineageTag: 20f40f7d-0642-4e81-a77d-8215c552039b

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: aefc1cec-a9f0-471f-b3cc-43c3679e7f66
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Click
		dataType: int64
		formatString: 0
		lineageTag: cb1a23f0-891a-4c75-8fb7-9e325f405fe9
		summarizeBy: sum
		sourceColumn: Click

		annotation SummarizationSetBy = Automatic

	column Conversion
		dataType: int64
		formatString: 0
		lineageTag: 79d20d49-9c94-4e12-b4fa-cf9cd5bafb2f
		summarizeBy: sum
		sourceColumn: Conversion

		annotation SummarizationSetBy = Automatic

	column Id_detalle
		dataType: string
		lineageTag: ddb8f793-6b81-4f9c-bde8-0fbc6367a6f0
		summarizeBy: none
		sourceColumn: Id_detalle

		annotation SummarizationSetBy = Automatic

	partition 'Dataset Marketing' = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\MSI\Documents\GitHub\Portafolio-Profesional\Marketing Campaign Analysis\Data\dataset_marketing_2025_500k.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Fecha", type date}, {"Campaign", type text}, {"Channel", type text}, {"City", type text}, {"Device", type text}, {"Ads", type text}, {"Impresion", Int64.Type}, {"Click", Int64.Type}, {"Conversion", Int64.Type}}),
				    #"Columnas combinadas" = Table.CombineColumns(#"Tipo cambiado",{"Campaign", "Channel", "City", "Device", "Ads"},Combiner.CombineTextByDelimiter("-", QuoteStyle.None),"Id_detalle"),
				    #"Columnas quitadas1" = Table.RemoveColumns(#"Columnas combinadas",{"Impresion", "ID_Detalle"})
				in
				    #"Columnas quitadas1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

