table Priority
	lineageTag: 5fbb3bf1-71e8-43ae-a916-d40405c7fb7f

	column ID_Priority
		dataType: int64
		formatString: 0
		lineageTag: 841075a6-f818-487a-a04d-3666e98d6778
		summarizeBy: none
		sourceColumn: ID_Priority

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: cd1ce215-4b3a-4121-a861-6247adaaa0dc
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column 'Priority 2'
		dataType: string
		lineageTag: 12a2f170-608e-4bad-9cb0-eb4e029af720
		summarizeBy: none
		sourceColumn: Priority 2

		annotation SummarizationSetBy = Automatic

	partition Priority = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUfLJL1eK1YlWMgKyfVNTMktzwVxjINcjMz1DKTYWAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID_Priority = _t, Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"ID_Priority", Int64.Type}, {"Columna1", type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"Columna1", "Priority"}}),
				    #"Columna duplicada" = Table.DuplicateColumn(#"Columnas con nombre cambiado", "Priority", "Priority - Copia"),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Columna duplicada",{{"Priority - Copia", "Priority 2"}})
				in
				    #"Columnas con nombre cambiado1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

