table Segmentador
	lineageTag: 5e65f995-9bf0-4e53-9d82-bf42a81db774

	column Segmento
		dataType: string
		lineageTag: 6b79a8ea-0366-43c7-aa02-42d87e6eb325
		summarizeBy: none
		sourceColumn: Segmento
		sortByColumn: Índice

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column ID_seg
		dataType: string
		lineageTag: 106ae582-c823-4b9c-a1c1-0cbe374d0351
		summarizeBy: none
		sourceColumn: ID_seg

		annotation SummarizationSetBy = Automatic

	column Índice
		dataType: int64
		formatString: 0
		lineageTag: 2d82b0ee-f2d5-4804-ae76-1c347219fd46
		summarizeBy: none
		sourceColumn: Índice

		annotation SummarizationSetBy = Automatic

	partition Segmentador = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wci5KTSxJTVEIyUzOTi1R0lFyDlGK1YlWcsssKi5RCEotLsjPK04FirsFgcWBIvk5pSWZ+XlAMYhQcGlRWWolkBsM5jrn5BfDDSwGmegDNDIWAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Segmento = _t, ID_seg = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Segmento", type text}, {"ID_seg", type text}}),
				    #"Índice agregado" = Table.AddIndexColumn(#"Tipo cambiado", "Índice", 1, 1, Int64.Type)
				in
				    #"Índice agregado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

