table Source
	lineageTag: 2244d908-c60d-4420-a4fd-1103efe1f366

	column ID_Source
		dataType: int64
		formatString: 0
		lineageTag: a2865cec-9891-4538-b938-e0bbb0698bb5
		summarizeBy: none
		sourceColumn: ID_Source

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: 4d3d1340-5486-46ee-adb2-a671bb74ed43
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column 'Source 2'
		dataType: string
		lineageTag: d7600ea8-7910-4835-85cc-c9b84fdbd5bf
		summarizeBy: none
		sourceColumn: Source 2

		annotation SummarizationSetBy = Automatic

	partition Source = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUXLOSCxRitWJVjICcgIy8vNSwTxjIM81NzEzRyk2FgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID_Source = _t, Source = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"ID_Source", Int64.Type}, {"Source", type text}}),
				    #"Columna duplicada" = Table.DuplicateColumn(#"Tipo cambiado", "Source", "Source - Copia"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columna duplicada",{{"Source - Copia", "Source 2"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

