table 'Status FR'
	lineageTag: b53f2ca0-dc24-4724-a4f2-2aba6c68bc13

	column ID_Status
		dataType: int64
		formatString: 0
		lineageTag: 806b1f77-b3b6-443d-a88b-c2486f440bbc
		summarizeBy: none
		sourceColumn: ID_Status

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 1c880a67-9dcf-40d2-bdfc-c1c6ee3025ab
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition 'Status FR' = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlDSUSrPLMnIzFMI9nFUitWJVjIECgHZCmGZ+TmJJakpYEFLoKBffl6qUmwsAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID_Status = _t, Status = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"ID_Status", Int64.Type}, {"Status", type text}}),
				    #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado", each ([ID_Status] <> 9))
				in
				    #"Filas filtradas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

